### ISSUE TITLE
Use RTree instead of KDTree

### ISSUE THREAD

**Issue by ocefpaf** [pyoceans/tardis#10]
RTree seems to be more adequate for bbox searches.

**Comment by ocefpaf** [comment]
The latest changes in scipy's kdtree makes it more suitable for this task.

**Comment by kwilcox** [comment]
Was this the changes in 0.17 that made kdtree much faster or something newer? My real question is if I should be using kdtree over rtree for bbox searches.

**Comment by ocefpaf** [comment]
For my cases, because the model grid points do not change with time, latesr
scipy KDTree is faster. I guess that the RTree is still a better option if
you are adding or removing points from the original tree.

On Jul 2, 2017 4:17 PM, "Kyle Wilcox" <notifications@github.com> wrote:

Was this the changes in 0.17 that made kdtree much faster or something
newer? My real question is if I should be using kdtree over rtree for bbox
searches.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/pyoceans/tardis/issues/10#issuecomment-312511316>, or mute
the thread
