### ISSUE TITLE
Issue new release of tardis 

### ISSUE THREAD

**Issue by rsignell-usgs** [pyoceans/tardis#26]
@ocefpaf , would be nice to get a new release of tardis (and updated conda package) so that `from tardis.slices ...` would work,  so that I could test
https://gist.github.com/ocefpaf/872140f7dd808c45fbfbed2b709d6546

**Comment by ocefpaf** [comment]
@rsignell-usgs I am not going to make a conda package yet b/c I am changing a lots of stuff here. But you should be able to run the notebook by installing the latest bugfix release with:

`pip install https://github.com/pyoceans/tardis/archive/v0.3.1.tar.gz`
